"""
Report Agent - Final RCA Generation
Generates the Root Cause Analysis markdown report.
"""

from datetime import datetime
from langchain_core.messages import AIMessage
from ..state import IncidentState


async def report_agent(state: IncidentState) -> dict:
    """
    Report phase: Generate comprehensive RCA report.
    This is the final node in the graph.
    """
    alert_id = state["alert_id"]
    service_name = state["service_name"]
    root_cause = state["root_cause"]
    severity = state["severity"]
    initial_severity = state.get("checkpoint_state", {}).get("severity", 1.0)
    mitigation_plan = state["mitigation_plan"]
    actions_executed = state["actions_executed"]
    log_summary = state["log_summary"]
    metrics_summary = state["metrics_summary"]
    deployment_changes = state["deployment_changes"]
    health_passed = state["health_check_passed"]
    
    # Generate RCA markdown
    rca_report = f"""
# Root Cause Analysis Report

## Incident Summary
| Field | Value |
|-------|-------|
| **Alert ID** | {alert_id} |
| **Service** | {service_name} |
| **Status** | {'✅ RESOLVED' if health_passed else '⚠️ REQUIRES ATTENTION'} |
| **Generated** | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |

## Severity Timeline
- **Initial Severity:** {initial_severity:.2f}/1.0
- **Final Severity:** {severity:.2f}/1.0
- **Improvement:** {((initial_severity - severity) / initial_severity * 100):.1f}%

## Root Cause
{root_cause}

## Evidence Summary

### Metrics
{metrics_summary if metrics_summary else 'N/A'}

### Logs
{log_summary if log_summary else 'N/A'}

### Configuration Changes
{chr(10).join(f"- {d.get('description', 'N/A')} ({d.get('timestamp', 'N/A')})" for d in deployment_changes) if deployment_changes else 'No recent changes detected'}

## Mitigation Actions
{chr(10).join(mitigation_plan) if mitigation_plan else 'No mitigation performed'}

## Actions Executed
| Action | Status | Details |
|--------|--------|---------|
{chr(10).join(f"| {a['action']} | {a['status']} | {a['details']} |" for a in actions_executed) if actions_executed else '| N/A | N/A | N/A |'}

## Recommendations
1. **Immediate:** {'No further action required' if health_passed else 'Manual investigation recommended'}
2. **Short-term:** Add alerting for connection pool exhaustion
3. **Long-term:** Implement configuration change review process

---
*Report generated by Autonomous Incident Commander*
"""
    
    report_message = f"""
📝 **RCA REPORT GENERATED**

**Status:** {'✅ Incident Resolved' if health_passed else '⚠️ Requires Manual Review'}
**Severity Reduced:** {initial_severity:.2f} → {severity:.2f}

The full RCA report has been generated and saved.
"""
    
    return {
        "rca_report": rca_report,
        "current_phase": "complete",
        "messages": [AIMessage(content=report_message)]
    }
